### ISSUE TITLE
Issue with unicode attribute

### ISSUE THREAD

**Issue by mm-tom** [shinnn/node-font2svg#1]
I've run in to an issue with the following line on index.js:

```
          for (var i = 1; i < glyphs.length; i++) {
             glyphs[i].$.unicode = '&#' + uniquePoints[i] + ';';
          }
```

Is this supposed to be generating a valid character code for the glyph?

I've found that when cross referencing the generated svg font file to the source file, that this is attribute does not use the same character code.

Removing this altogether has fixed the issue for me, as it leaves a valid unicode character for the attribute.

**Comment by shinnn** [comment]
> Is this supposed to be generating a valid character code for the glyph?

Yes.
